"""add conversion job timing fields

Revision ID: 68ec4a798163
Revises: cb5800731b47
Create Date: 2026-04-20 21:19:30.702489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ec4a798163'
down_revision = 'cb5800731b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
