"""add ocr_enabled to conversion_jobs

Revision ID: 8696a7483aa6
Revises: 68ec4a798163
Create Date: 2026-04-21 01:30:12.406920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8696a7483aa6'
down_revision = '68ec4a798163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.drop_column('ocr_enabled')

    # ### end Alembic commands ###
