"""add file_assets table

Revision ID: 988fea454445
Revises: 
Create Date: 2026-04-20 01:42:44.050975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988fea454445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_assets_extension'), ['extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_mime_type'), ['mime_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_public_id'))
        batch_op.drop_index(batch_op.f('ix_file_assets_mime_type'))
        batch_op.drop_index(batch_op.f('ix_file_assets_extension'))

    op.drop_table('file_assets')
    # ### end Alembic commands ###
