"""add conversion_jobs and conversion_results tables

Revision ID: cb5800731b47
Revises: 988fea454445
Create Date: 2026-04-20 17:37:27.757276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5800731b47'
down_revision = '988fea454445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('requested_output_format', sa.String(length=20), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_jobs_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversion_jobs_requested_output_format'), ['requested_output_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_jobs_status'), ['status'], unique=False)

    op.create_table('conversion_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('output_filename', sa.String(length=255), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_zip_bundle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['conversion_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['file_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('output_path')
    )
    with op.batch_alter_table('conversion_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_results_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_results_output_format'), ['output_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_results_source_file_id'), ['source_file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_results_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_conversion_results_output_format'))
        batch_op.drop_index(batch_op.f('ix_conversion_results_job_id'))

    op.drop_table('conversion_results')
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_conversion_jobs_requested_output_format'))
        batch_op.drop_index(batch_op.f('ix_conversion_jobs_public_id'))

    op.drop_table('conversion_jobs')
    # ### end Alembic commands ###
